[workspace]
members = [
    "ramhorns",
    "ramhorns-derive",
    "tests",
]

[profile]
release = { lto = true }
bench = { lto = true }

[patch.crates-io]
ramhorns-derive = { path = "./ramhorns-derive" }
